from math import *
#1-misol
t=int(input('T='))
l=int(input('L='))
r=3*t**2+3*l**5+4.9
print(r)
#2-misol
p=int(input('P='))
y=int(input('Y='))
k=log(p**2+y**3)+exp(p)
print(k)
#3-misol
n=int(input('N='))
y=int(input('Y='))
g=n*(y+3.5)+sqrt(y)
print(g)
#4-misol
a=int(input('A='))
t=int(input('T='))
d=9.8*a**2+5.28*cos(t)**5
print(d)
#5-misol
x=int(input('X='))
l=1.51*cos(x)**2+2*x**3
print(l)
#6-misol
y=int(input('Y='))
x=int(input('X='))
m=cos(2*y)+3.6*exp(x)
print(m)
#7-misol
m=int(input('M='))
n=m**2+2.8*abs(m)+0.55
print(n)
#8-misol
y=int(input('Y='))
t=sqrt(abs(6*y**2-0.1*y+4))
print(t)
#9-misol
x=int(input('X='))
y=int(input('Y='))
v=log(y+0.95)+sin(x)**4
print(v)
#10-misol
k=int(input('K='))
x=int(input('X='))
y=int(input('Y='))
u=exp(y)+7.355*k**2+sin(x)*sin(x)
print(u)
#11-misol
y=int(input('Y='))
x=int(input('X='))
s=9.756*y**7+2*tan(x)
print(s)
#12-misol
t=int(input('T='))
x=int(input('X='))
k=7*t**2+3*sin(x)**3+9.2
print(k)
#13-misol
y=int(input('Y='))
e=sqrt(abs(3*y**2+0.5*y+4))
print(e)
#14-misol
x=int(input('X='))
y=int(input('Y='))
r=abs(sqrt(sin(y)*sin(y)+6.835+exp(x)))
print(r)
#15-misol
y=int(input('Y='))
h=sin(y)**2-2.8*y+sqrt(abs(y))
print(h)
#16-misol
y=int(input('Y='))
s=sqrt(cos(4*y**2)+7.151)
print(s)
#17-misol
y=int(input('Y='))
n=3*y**2+sqrt(y+1)
print(n)
#18-misol
y=int(input('Y='))
z=3*y**2+sqrt(y**3+1)
print(z)
#19-misol
n=int(input('N='))
y=int(input('Y='))
g=int(input('G='))
p=n*sqrt(y**3+1.09*g)
print(g)
#20-misol
x=int(input('X='))
y=int(input('Y='))
k=int(input('K='))
u=exp(k+y)+tan(x*sqrt(y))
print(u)
#21-misol
y=int(input('Y='))
h=int(input('H='))
p=exp(y+5.5)+9.1*h**3
print(p)
#22-misol
x=int(input('X='))
y=int(input('Y='))
u=int(input('U='))
t=sin(2*u)*log(2*y**2+sqrt(x))
print(t)
#23-misol
y=int(input('Y='))
f=int(input('F='))
g=exp(2*y)+sin(f)
print(g)
#24-misol
y=int(input('Y='))
f=2*sin(0.214*y**5+1)
print(f)
#25-misol
y=int(input('Y='))
f=int(input('F='))
g=exp(2*y)+sin(f**2)
print(g)
#26-misol
p=int(input('P='))
z=sin(p**2+0.4)**3
print(z)
#27-misol
x=int(input('X='))
y=int(input('Y='))
v=int(input('V='))
w=1.03*v+exp(2*y)+tan(abs(x))
print(w)
#28-misol
y=int(input('Y='))
h=int(input('H='))
t=exp(y+h)+sqrt(abs(6.4*y))
print(t)
#29-misol
y=int(input('Y='))
n=3*y**2+sqrt(abs(y+1))
print(n)
#30-misol
y=int(input('Y='))
r=int(input('R='))
w=exp(y+r)+7.2*sin(r)
print(w)
