from math import *
from time import *
from random import *
'''#1(a)-misol
sleep(.4)
print('1(a)-misol')
sleep(.4)
x=int(input('x = '))
sleep(.4)
u=(sin(x)**3)+(cos(x)**3)+tan(x**2)/pow((2*sin(x)+(x**2)*cos(x)**2),1/3)
print(f'Javob: {u} ga teng')
#1(b)-misol
sleep(.4)
print('1(b)-misol')
sleep(.4)
a=int(input('a = '))
sleep(.4)
b=int(input('b = '))
sleep(.4)
x=int(input('x = '))
z=((a*x**3)+b*pow(x**2,1/3)*(cos(x)**2)+1/x)**a
sleep(.4)
print(f'Javob: {z} ga teng')
#2(a)-misol
sleep(.4)
print('2(a)-misol')
sleep(.4)
x=int(input('x = '))
y=(sqrt(sin(sqrt(x))+x**3)/log(cos((x**2+0.5)**2)**2))**3
sleep(.4)
print(f'Javob: {y} ga teng')
#2(b)-misol
sleep(.4)
print('2(b)-misol')
sleep(.4)
x=int(input('x = '))
sleep(.4)
y=int(input('y = '))
sleep(.4)
k=int(input('k = '))
t=(exp(-x**2)*sin(k*x)**2/x**2+2*y**2+3)
sleep(.4)
print(f'Javob: {t} ga teng')
#3(a)-misol
sleep(.4)
print('3(a)-misol')
sleep(.4)
a=int(input('a = '))
sleep(.4)
b=int(input('b = '))
sleep(.4)
c=int(input('c = '))
sleep(.4)
x=int(input('x = '))
z=(a*pow(sin(x)**2,1/5)-log(b*sin(x))**2/pow((a**2+b**2+c**2)**2,1/3))
sleep(.4)
print(f'Javob: {z} ga teng')
#3(b)-misol
sleep(.4)
print('3(b)-misol')
sleep(.4)
y=int(input('y = '))
sleep(.4)
k=int(input('k = '))
sleep(.4)
x=int(input('x = '))
t=(exp(-x**2)*sin(k*x)**2)/((x**2)+2*(y**2)+3)
print(f'Javob: {t} ga teng')
#4(a)-misol
sleep(.4)
print('4(a)-misol')
sleep(.4)
x=int(input('x = '))
u=((atan(x)**3)+1.1*sec*(pow(x,1/3)))**2/(log(1.1*x)+log(1.2*x**4)**3)
sleep(.4)
print(f'Javob: {u} ga teng')
#4(b)-misol
sleep(.4)
print('4(b)-misol')
sleep(.4)
x=int(input('x = '))
sleep(.4)
a=int(input('a = '))
sleep(.4)
b=int(input('b = '))
t=(2*x+3*cos(x+1))/(abs(1+(x+1))**2)+(a*b*x**2)
sleep(.4)
print(f'Javob: {t} ga teng')
#5(a)-misol
sleep(.4)
print('5(a)-misol')
sleep(.4)
x=int(input('x = '))
y=(2.15*cos(x)-0.45*acos(x**3))/(3.4*pow(x,1/5)*exp(cos(x))+log(3.9+x**3)**2)
sleep(.4)
print(f'Javob: {y} ga teng')
#5(b)-misol
sleep(.4)
print('5(b)-misol')
sleep(.4)
x=int(input('x = '))
sleep(.4)
y=int(input('y = '))
t=(exp(-x**2)*sin(cos(x**2))**2)/(pow(x+2*y**2,1/4))
sleep(.4)
print(f'Javob: {t} ga teng')
#6(a)-misol
sleep(.4)
print('6(a)-misol')
sleep(.4)
x=int(input('x = '))
y=(2.5*sin(x)+0.75*tan(x**3)**2)/(0.65*pow(x,1/3)*exp(sin(x))+cos(x**3)**2)
sleep(.4)
print(f'Javob: {y} ga teng.')
#6(b)-misol
sleep(.4)
print('6(b)-misol')
sleep(.4)
x=int(input('x = '))
sleep(.4)
z=int(input('z = '))
v=(x**(-z**2)+z**(-x**3)+cos(x**2))/(exp((x**2)-(z**2))+exp((x**2)-(z**2)))
sleep(.4)
print(f'Javob: {v} ga teng.')
'''#7(a)-misol
